fname=input("enter first name")
lname=input("enter last name")
age=int(input("enter age"))
city=input("enter city")
print(("your name is %s %s\nyour age is %d\nyou live in %s") % (fname,lname,age,city))
